# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
  - cd pkg/retistruct
addons:
  apt:
    packages:
      - mesa-common-dev
      - libglu1-mesa-dev
